print("##############################")
print("#                            #")
print("#  Putri Deissyta Herliyana  #")
print("#        2510817320010       #")
print("#                            #")
print("##############################")